-- Create Warehouse
CREATE WAREHOUSE IF NOT EXISTS DEMO_WH
WITH WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

-- Create Database
CREATE DATABASE IF NOT EXISTS DEMO_DB;

-- Create Schema
CREATE SCHEMA IF NOT EXISTS DEMO_DB.DEMO_SCHEMA;

-- Use objects
USE WAREHOUSE DEMO_WH;
USE DATABASE DEMO_DB;
USE SCHEMA DEMO_SCHEMA;

-- Create table
CREATE OR REPLACE TABLE EMPLOYEE (
    ID INT,
    NAME STRING,
    SALARY NUMBER,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);