CREATE OR REPLACE PROCEDURE DEMO_DB.DEMO_SCHEMA.LOAD_EMPLOYEE()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN

CREATE OR REPLACE TABLE EMPLOYEE (
    ID INT,
    NAME STRING,
    SALARY NUMBER,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO DEMO_DB.DEMO_SCHEMA.EMPLOYEE (ID, NAME, SALARY)
VALUES
(1, 'John', 5000),
(2, 'Mike', 6000),
(3, 'Sara', 7000);

RETURN 'EMPLOYEE DATA LOADED';

END;
$$;