name: Deploy Snowflake SP

on:
  push:
    branches:
      - main
    paths:
      - 'snowflake/**'

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    
    - name: List files
      run: ls -la

    - name: Install dependencies
      run: |
        pip install -r .snowflake/requirements.txt

    - name: Deploy to Snowflake
      env:
        SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
        SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
        SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_WAREHOUSE: DEMO_WH
        SNOWFLAKE_DATABASE: DEMO_DB
        SNOWFLAKE_SCHEMA: DEMO_SCHEMA
      run: |
        python scripts/deploy_snowflake.py